#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tb?useUnicode=true&characterEncoding=utf8&usessl=true #&useSSL=false
    username: root
    password: 123456
  #邮箱配置
  mail:
    host: smtp.163.com
    username: coreyxuyong@163.com
    password: yourPassword163
    default-encoding: utf-8
  activemq:
    broker-url: tcp://127.0.0.1:61616  #地址
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100  #线程池
  #default point to point
  jms:
    pub-sub-domain: true
  redis:
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  output:
    ansi:
      enabled: always

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.itcorey.pojo
  mapperLocations: classpath:mappers/*.xml


#端口
server:
  port: 8081
logging:
  config: classpath:logback-spring.xml

