#\u914D\u7F6E\u6570\u636E\u6E90
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  #\u90AE\u7BB1\u914D\u7F6E
  mail:
    host: smtp.163.com
    username: coreyxuyong@163.com
    password: yourPassword163
    default-encoding: utf-8

#\u516C\u5171\u914D\u7F6E\u4E0Eprofiles\u9009\u62E9\u65E0\u5173 mapperLocations\u6307\u7684\u8DEF\u5F84\u662Fsrc/main/resources
mybatis:
  typeAliasesPackage: com.itcorey.pojo
  mapperLocations: classpath:mappers/*.xml





